[package]
name = "my-gtk-app"
version = "0.1.0"
authors = ["Fernando Marca Magalhães <fernandomarca@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gtk]
version = "0.1"
package = "gtk4"
